spring :
  application :
    name : an-rest-service
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: # To be define in application-'profil'.yml
            clientSecret: # To be define in application-'profil'.yml

ariadnext:
  idcheckio:
    client:
      username : # To be define in application-'profil'.yml
      password : # To be define in application-'profil'.yml
      plateform : # prod, test or sandbox - To be define in application-'profil'.yml



